name: CI - Test & Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Remove node_modules and package-lock.json
        run: |
          rm -rf node_modules
          rm -f package-lock.json
        working-directory: rebel-extension

      - name: Install dependencies
        run: npm install
        working-directory: rebel-extension

      - name: Build project (Vite)
        run: npm run build
        working-directory: rebel-extension

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install
        working-directory: rebel-extension

      - name: Run tests
        run: npm test
        working-directory: rebel-extension

  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Adjust to your Python version if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: rebel-extension  # Adjust if your Python project is in a different directory

      - name: Install pytest
        run: pip install pytest

      - name: Run pytest
        run: pytest  # Run pytest to execute the tests
        working-directory: rebel-extension  # Adjust if your tests are located elsewhere

